### PR TITLE
ci: Added pypi actions

### PR DESCRIPTION
**Pull request by marksweb**
Before merging this needs 2 keys generating from pypi and adding to the repo secrets.

### CODE REVIEW

**Comment by fsbraun** [comment]
Do we need this secrets from my pypi account?

**Comment by marksweb** [comment]
@fsbraun They need to be generated from a user who maintains the necessary access for the actions to run.

Generally I've been creating these tokens from the django-cms account, but you could generate them. 

A token needs to be created on test.pypi.org and then pypi.org

Tokens can be created in a user's account section and I believe it's good practice to limit a key to a specific project. This often means you need to build & publish to test.pypi.org manually the first time because most projects don't use that.

**Comment by marksweb** [comment]
@fsbraun Ok I've added the two tokens. When this merges you'll see the test workflow kick off & the package will release to here; https://test.pypi.org/project/djangocms-frontend/

Then we can make use of github releases to get future builds out to pypi.org

**Review by fsbraun — APPROVED** [review]

**Comment by fsbraun** [comment]
How or when are the pypi actions triggered?

**Comment by marksweb** [comment]
Need to remember to respond here @fsbraun

**Comment by marksweb** [comment]
I need to remember to respond here @fsbraun 😬

**Comment by marksweb** [comment]
So the details of how this works @fsbraun...

When a Pull Request is merged to the main branch the test build is triggered;

```
on:
  push:
    branches:
      - main
```

This action builds the application;

`python -m build --sdist --wheel --outdir dist/ .`

Then the package is uploaded here; https://test.pypi.org/project/djangocms-frontend/

That completes the workflow. At this point you can see that the merged PR didn't break the build and it can be uploaded to pypi. If you wanted to, you could then install/download the uploaded package to test it.

The second workflow included in this PR will build and release the application to pypi.org triggered by a published github release;

```
on:
  release:
    types:
      - published
```

So the scenario which would get you to the point where this is triggered might be;

- PRs merged
- Version bump/change log etc updated (via a PR)
- Main branch verified as ready for a release
- Release drafted; https://github.com/django-cms/djangocms-frontend/releases/new
- Hit that green "Publish release" button

That final step then is the trigger for the action and the release workflow will start.

New release can then be found on here; https://pypi.org/project/djangocms-frontend/

**Comment by fsbraun** [comment]
Thanks very much @marksweb ! Looks great! From now on GitHub and pypi releases in sync! 👍

**Pull request merged**
