### PR TITLE
fix: navigation template to get correct menu display

### PR DESCRIPTION
**Pull request by rolandf**
Small change to fix navigation plugin menu.

### CODE REVIEW

**Comment by fsbraun** [comment]
@rolandf Can you check why the tests fail?

**Comment by rolandf** [comment]
Sorry I don't understand how changing just two html tags in a template generate  so much errors. My TemplateFix branch was created from a point in time where frontend_form was still in djangocms_frontend, not from the latest branch. Is that the reason ?

**Comment by fsbraun** [comment]
I think the unit test for navigation has to be adapted to the new template. This unit test feels for all this cases of course. Can you look at the test for navigation? Thank you so much!

**Comment by marksweb** [comment]
@rolandf having a quick look at the change vs the failure message, the test expects an empty div with a class of container. Following this change I think what it's getting is the container div with the ul tag inside.

**Comment by rolandf** [comment]
Sorry but I don't get it.
I did manage.py test and no errors come up.

**Comment by fsbraun** [comment]
Sorry, it's `python run_tests.py` in the package directory (`../ djangocms-frontend`).

**Comment by rolandf** [comment]
@fsbraun  Thank you for the head up. I made an update to the test on my branch. I see a mention of that in this pull request, is that all or is there a new action needed from me to have github relaunch tests and see if they pass ?

**Review by fsbraun — APPROVED** [review]
Thanks @rolandf ! This looks good. If you push commits to your repo which you used to create the PR these commits are automatically added to the PR. So no further action needed.

The new djlint test fails. This is already taken care of in another PR (#66), so not to worry about here.

**Pull request merged**
